### ISSUE TITLE
alignment with DataCite metadata schema v4.1

### ISSUE THREAD

**Issue by joschirr** [openaire/guidelines-literature-repositories#1]
to consider in the guidelines some useful additions from the DataCite metadata schema v4.1
- new relationTypes (IsDescribedBy / Describes; HasVersion / IsVersionOf; IsRequiredBy / Requires)
- nameType attribute for creator and contributor elements
- relatedIdentifier attribute for resourceTypeGeneral element
- lang attribute to Rights property

**Comment by ACz-UniBi** [comment]
Published as "OpenAIRE Guidelines for institutional and thematic repository managers 4.0" , Nov. 2018 at

https://doi.org/10.5281/zenodo.1299203
