### ISSUE TITLE
Explain abbreviations

### ISSUE THREAD

**Issue by vpeil** [openaire/guidelines-literature-repositories#4]
Although it might be clear the document should introduce the meaning of

- (M)
- (MA)
- (O)
- (R)

I couldn't find these explanations.

**Comment by ioverka** [comment]
Some of the field descriptions explain it in the "usage" section though, see http://openaire-guidelines-for-literature-repository-managers.readthedocs.io/en/latest/field_subject.html#dc-subject

**Comment by joschirr** [comment]
done in https://openaire-guidelines-for-literature-repository-managers.readthedocs.io/en/latest/application_profile.html
