### ISSUE TITLE
Relation between License Condition, Access Rights and Embargo Period Date

### ISSUE THREAD

**Issue by ioverka** [openaire/guidelines-literature-repositories#6]
Questions:

1. Why is Embargo Period Date (M) and not (MA)?
2. Access Rights: Can't "embargoed access" been derived from "open access" and the existance of an "Embargo Period Date"
3. Have you had a look at Crossref's handling of embargos as part of the license statement? Might be an interesting approach for this scenario as well, see https://github.com/CrossRef/rest-api-doc/blob/447cdbd0d5f61f256dfe12952d9c3d8076cd38d3/funder_kpi_metadata_best_practice.md#embargoes

**Comment by joschirr** [comment]
1.  fixed. It is now (MA)
2. It could, but for the time being we use dataCite:date properties to express the embargo period
3. a new property oaire:licenseCondition is introduced with attribute startDate. Thanks for the hint.
