### ISSUE TITLE
application_profile.rst: link not working

### ISSUE THREAD

**Issue by mrustl** [openaire/guidelines-literature-repositories#7]
The link to [http://namespaceopenaire.eu/schema/oaire](http://namespaceopenaire.eu/schema/oaire)  is not working in the **document application_profile.rst**

**Comment by ACz-UniBi** [comment]
Dear @mrustl , thank you for your issue you pointed out here. However, for the NameSpaces, there is no obligation according to W3C guidelines that they are resolvable via "browser". It is important to distinguished elements. 
We will consider it as a possibility.

Best regards, Andreas
