### ISSUE TITLE
Element fundingStream must be removed

### ISSUE THREAD

**Issue by mpbraendle** [openaire/guidelines-literature-repositories#8]
The element fundingStream as a child element of <datacite:fundingReference> must be removed.
It is not compatible with the DataCite Metadata Schema 4.x and any validator that validates against https://schema.datacite.org/meta/kernel-4.1/metadata.xsd will complain.

**Comment by joschirr** [comment]
In the context of the literature repository guidelines we do not validated against 
https://schema.datacite.org/meta/kernel-4.1/metadata.xsd
but
https://github.com/openaire/guidelines-literature-repositories/blob/master/schemas/openaire-v4.xsd
We only "borrow" and re-use some elements and vocabularies from the DataCite schema.
